export const quizImages = [
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/9c1b19682ecf926c296f520d5d6e0972_images.jpg",
    gender: "Men",
    baseColour: "Grey",
    articleType: "Tshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/06e9d4231254fdb2c7fe967ad413ad7b_images.jpg",
    gender: "Men",
    baseColour: "Green",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/59912a0287751ff0475c8748dbcf4ea0_images.jpg",
    gender: "Men",
    baseColour: "Grey",
    articleType: "Sweatshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/3af9f145845d8453a066322de35980af_images.jpg",
    gender: "Men",
    baseColour: "Navy Blue",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/9584fab8cde60a77e797973020e5c91d_images.jpg",
    gender: "Men",
    baseColour: "Red",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image:
      "https://assets.myntassets.com/v1/images/style/properties/1c40d2b94c58f8037380b197a26f567d_images.jpg",
    gender: "Men",
    baseColour: "White",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image:
      "https://assets.myntassets.com/v1/images/style/properties/5929783c109080d3d56a96f2621e3c1a_images.jpg",
    gender: "Men",
    baseColour: "Maroon",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image:
      "https://assets.myntassets.com/v1/images/style/properties/abe4da872e3c1f9bf2f8015b408248d7_images.jpg",
    gender: "Men",
    baseColour: "Beige",
    articleType: "Kurtas",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/c1fabaa873d812a3e16674928f26a764_images.jpg",
    gender: "Men",
    baseColour: "Green",
    articleType: "Kurtas",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/2d986dbf9e5f64e3ab8471120c557db4_images.jpg",
    gender: "Men",
    baseColour: "Black",
    articleType: "Tshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/ef754e63472dece06abfa6d6c1266d91_images.jpg",
    gender: "Men",
    baseColour: "Yellow",
    articleType: "Tshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/6a4ba6f42c04311003248ed463d694d7_images.jpg",
    gender: "Men",
    baseColour: "Black",
    articleType: "Blazers",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/b84ff60e9a3642237a53b4bf92652fcd_images.jpg",
    gender: "Men",
    baseColour: "Olive",
    articleType: "Blazers",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/4850873d0c417e6480a26059f83aac29_images.jpg",
    gender: "Men",
    baseColour: "Blue",
    articleType: "Jeans",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/9e539f4fa57cfd97e48e0f5493a46151_images.jpg",
    gender: "Men",
    baseColour: "Black",
    articleType: "Jeans",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/d8879a06c95e34869b4228d5470bfb97_images.jpg",
    gender: "Men",
    baseColour: "Blue",
    articleType: "Jeans",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Fall",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/94218ed43f33a3f01c61df343a0260f3_images.jpg",
    gender: "Men",
    baseColour: "Grey",
    articleType: "Track Pants",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Fall",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/987d4390421e951dafe4bfdaba57f5fd_images.jpg",
    gender: "Men",
    baseColour: "Grey",
    articleType: "Trousers",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/Puma-Men-Black-Short_18d7937fb5d087ebe34d60c3818484bc_images.jpg",
    gender: "Men",
    baseColour: "Black",
    articleType: "Shorts",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image:
      "http://assets.myntassets.com/v1/images/style/properties/e5c4d1d6162192568cf3b0f8cad15a6f_images.jpg",
    gender: "Men",
    baseColour: "Beige",
    articleType: "Shorts",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/45ddbc6a15140556214e15923244755b_images.jpg",
    gender: "Women",
    baseColour: "Purple",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/Scullers-For-Her-Women-White-Striped-Shirt_b4833b5129730298114c075d80980d96_images.jpg",
    gender: "Women",
    baseColour: "White",
    articleType: "Shirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/b56e261f9206aa95e42c43f4e62d0e5a_images.jpg",
    gender: "Women",
    baseColour: "Pink",
    articleType: "Tshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/683aba986f6883e3a5c64fb97c994342_images.jpg",
    gender: "Women",
    baseColour: "Black",
    articleType: "Tshirts",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/fe446adf94f9beb301b61bfc75a70bfa_images.jpg",
    gender: "Women",
    baseColour: "Green",
    articleType: "Tops",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/5a76ef8930d8bd543d8f7e6f5383d390_images.jpg",
    gender: "Women",
    baseColour: "Beige",
    articleType: "Tops",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/3c92594cc9b62cba6a314a9ca9fd1e19_images.jpg",
    gender: "Women",
    baseColour: "White",
    articleType: "Tunics",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/70bd637a60298d4ba5b448841f21858a_images.jpg",
    gender: "Women",
    baseColour: "Brown",
    articleType: "Tunics",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/08a0c29d2ea67ca9449aa54466f6b0a1_images.jpg",
    gender: "Women",
    baseColour: "Green",
    articleType: "Kurtas",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/1dea61d01ec84aed63dcbb32adda717a_images.jpg",
    gender: "Women",
    baseColour: "Magenta",
    articleType: "Kurtas",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/Global-Desi-Women-Black-Top_54ac890a62a23d4ff28366029ce8146a_images.jpg",
    gender: "Women",
    baseColour: "Black",
    articleType: "Kurtis",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/cb7c67d2f4c52348332af9295125d830_images.jpg",
    gender: "Women",
    baseColour: "Orange",
    articleType: "Kurtis",
    masterCategory: "Apparel",
    subCategory: "Topwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/Jealous-21-Women-Black-Jeans_6c38590b2ec56b444a760aa56a8ef7e9_images.jpg",
    gender: "Women",
    baseColour: "Black",
    articleType: "Jeans",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/c3c02ca9eff02b8a9aed552288fe5914_images.jpg",
    gender: "Women",
    baseColour: "Blue",
    articleType: "Jeans",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/4044abbe79e8e12cc1beca06fae7bdc8_images.jpg",
    gender: "Women",
    baseColour: "Blue",
    articleType: "Churidar",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/8c29f66ec78e78081504b6ad73e6af8b_images.jpg",
    gender: "Women",
    baseColour: "Purple",
    articleType: "Leggings",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/07555cd5a97cd7ff5492fd344348dfcf_images.jpg",
    gender: "Women",
    baseColour: "Black",
    articleType: "Track Pants",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/4066aebdb467176a1e68e7b5c402130a_images.jpg",
    gender: "Women",
    baseColour: "Grey",
    articleType: "Skirts",
    masterCategory: "Apparel",
    subCategory: "Bottomwear",
    season: "Summer",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/FNF-Green-Collection-for-Wedding-Wear-Sari_6c60eef0b8d9cff87cfcd1f73953e5cd_images.jpg",
    gender: "Women",
    baseColour: "Grey",
    articleType: "Sarees",
    masterCategory: "Apparel",
    subCategory: "Saree",
    season: "Fall",
  },
  {
    image: "http://assets.myntassets.com/v1/images/style/properties/FNF-Pink---Yellow-Sari_04266265ca588ed869377b70fc7a3a38_images.jpg",
    gender: "Women",
    baseColour: "Yellow",
    articleType: "Sarees",
    masterCategory: "Apparel",
    subCategory: "Saree",
    season: "Fall",
  },
];
